/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Poem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'dateCreated' : Time,
  'author' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllPoems' : IDL.Func([], [IDL.Vec(Poem)], ['query']),
  'getPoemById' : IDL.Func([IDL.Nat], [Poem], ['query']),
  'submitPoem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Poem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'dateCreated' : Time,
    'author' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllPoems' : IDL.Func([], [IDL.Vec(Poem)], ['query']),
    'getPoemById' : IDL.Func([IDL.Nat], [Poem], ['query']),
    'submitPoem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };